const correctnessRules = {
  "array-callback-return": "error",
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-case-declarations": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": ["error", "except-parens"],
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-ex-assign": "error",
  "no-extra-boolean-cast": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-import-assign": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-new-native-nonconstructor": "error",
  "no-obj-calls": "error",
  "no-promise-executor-return": "error",
  "no-prototype-builtins": "error",
  "no-self-assign": "error",
  "no-setter-return": "error",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unreachable-loop": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-labels": "error",
  "no-unused-private-class-members": "error",
  "no-unused-vars": ["error", { args: "after-used", caughtErrors: "none" }],
  "no-useless-backreference": "error",
  "no-useless-catch": "error",
  "no-useless-escape": "error",
  "no-with": "error",
  "require-yield": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
};

const strictRules = {
  curly: ["error", "all"],
  "default-case-last": "error",
  eqeqeq: ["error", "always", { null: "ignore" }],
  "no-eval": "error",
  "no-implied-eval": "error",
  "no-new-func": "error",
  "no-new-wrappers": "error",
  "no-redeclare": "error",
  "no-return-assign": "error",
  "no-script-url": "error",
  "no-sequences": "error",
  "no-shadow": "error",
  "no-throw-literal": "error",
  "no-use-before-define": ["error", { functions: false }],
  "no-useless-call": "error",
  "no-useless-concat": "error",
  "no-useless-return": "error",
  "object-shorthand": "error",
  "prefer-arrow-callback": ["error", { allowNamedFunctions: true }],
  "prefer-const": "error",
  "prefer-object-spread": "error",
  "prefer-promise-reject-errors": "error",
  "prefer-template": "error",
  radix: "error",
  "require-await": "error",
  yoda: "error",
};

export default [
  {
    files: [
      "eslint.config.mjs",
      "scripts/*.cjs",
      "Assets/WebGLTemplates/Custom/*.js",
    ],
    languageOptions: { ecmaVersion: 2022 },
    linterOptions: { reportUnusedDisableDirectives: "error" },
    rules: { ...correctnessRules, ...strictRules },
  },
  {
    files: ["scripts/*.cjs"],
    languageOptions: {
      sourceType: "commonjs",
      globals: {
        Buffer: "readonly",
        URL: "readonly",
        WebSocket: "readonly",
        __dirname: "readonly",
        console: "readonly",
        fetch: "readonly",
        module: "readonly",
        process: "readonly",
        require: "readonly",
        setTimeout: "readonly",
      },
    },
  },
  {
    files: ["scripts/test-*.cjs"],
    rules: {
      // Async browser mocks deliberately return already-resolved values while
      // preserving the production API's Promise contract.
      "require-await": "off",
    },
  },
  {
    files: ["Assets/WebGLTemplates/Custom/*.js"],
    languageOptions: {
      sourceType: "script",
      globals: {
        AbortController: "readonly",
        Date: "readonly",
        Error: "readonly",
        JSON: "readonly",
        Number: "readonly",
        Promise: "readonly",
        Response: "readonly",
        URL: "readonly",
        caches: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        document: "readonly",
        fetch: "readonly",
        globalThis: "readonly",
        localStorage: "readonly",
        module: "readonly",
        navigator: "readonly",
        self: "readonly",
        setTimeout: "readonly",
        window: "readonly",
      },
    },
  },
];
