# Put scripts\unity-open.ps1 on PATH as the `unity-open` command AGENTS.md requires.
# Usage: .\scripts\install-unity-open.ps1 [-Force] [bin-directory]

[CmdletBinding()]
param(
    [switch]$Force,
    [Parameter(Position = 0)]
    [string]$BinDirectory
)

$ErrorActionPreference = "Stop"
$ScriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path
$SourcePath = [System.IO.Path]::GetFullPath((Join-Path $ScriptDirectory "unity-open.ps1"))

if (-not (Test-Path -LiteralPath $SourcePath)) {
    [Console]::Error.WriteLine("unity-open: missing $SourcePath")
    exit 2
}

if (-not $BinDirectory) {
    $BinDirectory = if ($env:UNITY_OPEN_BIN_DIR) {
        $env:UNITY_OPEN_BIN_DIR
    } else {
        Join-Path $HOME ".local\bin"
    }
}
New-Item -ItemType Directory -Path $BinDirectory -Force | Out-Null
$BinDirectory = [System.IO.Path]::GetFullPath($BinDirectory)

# The POSIX installer symlinks the script onto PATH. Windows symlinks need
# Developer Mode or an elevated shell, so write forwarding shims instead: a
# .cmd for PowerShell and cmd, and an extensionless one for Git Bash. Both name
# this clone's script by absolute path, which is what a symlink would have
# resolved to anyway.
$CmdPath = Join-Path $BinDirectory "unity-open.cmd"
$ShPath = Join-Path $BinDirectory "unity-open"

# A hand-written command already on PATH may be someone's own tool, so replacing
# it is an explicit choice rather than a side effect of running the installer.
foreach ($existing in @($CmdPath, $ShPath)) {
    if (-not (Test-Path -LiteralPath $existing)) {
        continue
    }

    $content = Get-Content -LiteralPath $existing -Raw -ErrorAction SilentlyContinue
    if ($content -and $content.Contains($SourcePath)) {
        continue
    }
    if (-not $Force) {
        [Console]::Error.WriteLine("unity-open: $existing already exists and does not point at $SourcePath")
        [Console]::Error.WriteLine("Re-run with -Force to replace it.")
        exit 3
    }
}

$cmdShim = "@echo off`r`npowershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$SourcePath`" %*`r`n"
[System.IO.File]::WriteAllText($CmdPath, $cmdShim, [System.Text.UTF8Encoding]::new($false))

# Git Bash reads the shebang, so this one keeps LF endings and no BOM.
$shShim = "#!/usr/bin/env bash`n" +
"# Generated by scripts/install-unity-open.ps1. Do not edit.`n" +
"exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File '$SourcePath' `"`$@`"`n"
[System.IO.File]::WriteAllText($ShPath, $shShim, [System.Text.UTF8Encoding]::new($false))

Write-Host "unity-open installed: $BinDirectory\unity-open[.cmd] -> $SourcePath"

$onPath = @($env:Path -split ';' | Where-Object { $_ } | ForEach-Object {
        try { [System.IO.Path]::GetFullPath($_.Trim('"')) } catch { $null }
    }) -contains $BinDirectory
if (-not $onPath) {
    [Console]::Error.WriteLine("Add $BinDirectory to PATH to run 'unity-open' by name.")
}

# Callers branch on exit 3 (a foreign unity-open), so always report a code.
exit 0
