"""Reuse an isolated project's caches while exactly syncing its authored inputs."""

from __future__ import annotations

import filecmp
import hashlib
import json
import shutil
import tempfile
from contextlib import contextmanager
from pathlib import Path

_MANAGED = ("Assets", "LocalPackages", "Packages", "ProjectSettings", "BuildContent.json")


def sync_tree(source: Path, destination: Path) -> None:
    """Remove stale inputs and leave byte-identical files (and their mtimes) alone."""
    if source.is_symlink() or destination.is_symlink():
        raise ValueError(f"Symlinks are not supported in reusable staging: {source}")
    if source.is_dir():
        if destination.exists() and not destination.is_dir():
            destination.unlink()
        destination.mkdir(parents=True, exist_ok=True)
        for child in destination.iterdir():
            if not (source / child.name).exists():
                if child.is_symlink() or child.is_file():
                    child.unlink()
                else:
                    shutil.rmtree(child)
        for child in source.iterdir():
            sync_tree(child, destination / child.name)
    else:
        if destination.is_dir():
            shutil.rmtree(destination)
        if not destination.exists() or not filecmp.cmp(source, destination, shallow=False):
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)


@contextmanager
def reuse_workspace(
    fresh: Path, source: Path, product: str, pipeline: str, targets: list[str], development: bool
):
    """Hold an exclusive lease through Unity execution; never copy another Library."""
    identity = {
        "source": str(source.resolve()),
        "product": product,
        "pipeline": pipeline,
        "targets": sorted(targets),
        "development": development,
        "unity": (fresh / "ProjectSettings/ProjectVersion.txt").read_text(),
    }
    encoded = json.dumps(identity, sort_keys=True)
    key = hashlib.sha256(encoded.encode()).hexdigest()[:12]
    workspace = fresh.parent / f"incremental-{product}-{pipeline}-{key}"
    lease = workspace.with_suffix(".lock")
    try:
        handle = lease.open("x")
    except FileExistsError as error:
        raise ValueError(f"Reusable build workspace is already leased: {lease}") from error
    try:
        with handle:
            handle.write(encoded)
        marker = workspace / ".release-workspace.json"
        if workspace.is_symlink() or (
            workspace.exists() and (not marker.is_file() or marker.read_text() != encoded)
        ):
            raise ValueError(f"Refusing to reuse an unrecognized workspace: {workspace}")
        if (workspace / "Temp/UnityLockfile").exists():
            raise ValueError(f"Close Unity before reusing its workspace: {workspace}")
        workspace.mkdir(parents=True, exist_ok=True)
        marker.write_text(encoded)
        for name in _MANAGED:
            sync_tree(fresh / name, workspace / name)
        # This directory was freshly generated by this invocation and is now fully synced.
        shutil.rmtree(fresh)
        yield workspace
    finally:
        lease.unlink()


def reset_shader_reports(stage: Path) -> None:
    for name in ("shader-stripping.json", "compute-shader-stripping.json"):
        (stage / "Temp" / name).unlink(missing_ok=True)


def preserve_shader_reports(stage: Path, output: Path) -> None:
    for name in ("shader-stripping.json", "compute-shader-stripping.json"):
        report = stage / "Temp" / name
        if report.is_file():
            shutil.copy2(report, output / name)


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def stage_inputs(
    source: Path, product: str, selection: tuple, stage_root: Path | None = None
) -> Path:
    source = source.resolve()
    plan, manifest, local = selection
    parent = (stage_root or source / "build/release-staging").resolve()
    parent.mkdir(parents=True, exist_ok=True)
    stage = Path(tempfile.mkdtemp(prefix=product + "-", dir=parent))
    # Assets contains shared host settings/editor tools; all game-owned content
    shutil.copytree(
        source / "Assets",
        stage / "Assets",
        ignore=shutil.ignore_patterns("LauncherConfig.txt", "LauncherConfig.txt.meta"),
    )
    shutil.copytree(source / "ProjectSettings", stage / "ProjectSettings")
    for name in plan["localPackages"]:
        shutil.copytree(
            local[name][0],
            stage / "LocalPackages" / name,
            ignore=shutil.ignore_patterns(
                "Tests", "Tests.meta", "Samples~", "Documentation~", "artifacts"
            ),
        )
    write_json(stage / "Packages/manifest.json", manifest)
    lock_path = source / "Packages/packages-lock.json"
    if lock_path.is_file():
        lock = json.loads(lock_path.read_text(encoding="utf-8-sig"))
        lock["dependencies"] = {
            name: value
            for name, value in lock.get("dependencies", {}).items()
            if (name not in local or name in plan["localPackages"])
            and name
            not in {
                "com.unity.pipeline",
                "com.unity.test-framework",
                "com.unity.testtools.codecoverage",
                "com.unity.ide.visualstudio",
            }
        }
        write_json(stage / "Packages/packages-lock.json", lock)
    write_json(stage / "BuildContent.json", plan)
    return stage
