using System;

namespace BudgetGameDev.Synth
{
    public enum MusicScale { Minor, Dorian, Pentatonic }

    [Serializable]
    public struct GameMusicState
    {
        public float Danger, EnemyProximity, PlayerHealth, MovementSpeed, Weather;
        public int NarrativeState;
    }

    /// <summary>
    /// Single control-thread owner. Produces sixteenth-note events on an engine-local
    /// frame clock. No scene access, audio processing or thread synchronization.
    /// Decisions are xorshift32 integer draws; Fill call chunking does not alter them.
    /// </summary>
    public sealed class MonoComposer
    {
        private static readonly int[] MinorIntervals = { 0, 2, 3, 5, 7, 8, 10 };
        private static readonly int[] DorianIntervals = { 0, 2, 3, 5, 7, 9, 10 };
        private static readonly int[] PentatonicIntervals = { 0, 3, 5, 7, 10 };
        private int sampleRate, root = 36, activeRoot = 36;
        private MusicScale scale, activeScale;
        private float tempo = 112, activeTempo = 112;
        private uint randomState;
        private long step;
        private double nextStepTime;
        private bool hasPendingOff;
        private SynthEvent pendingOff;
        private GameMusicState requested, smooth;
        private int densityBand, articulationBand, narrativeCandidate, candidateBeats, activeNarrative, motif;

        public MonoComposer(int sampleRate, uint seed) { Reset(sampleRate, seed); }

        public float Tempo { get { return tempo; } set { tempo = Finite(value, 40, 200, 112); } }
        public MusicScale Scale { get { return scale; } set { scale = (uint)value <= 2 ? value : MusicScale.Minor; } }
        public int RootMidi { get { return root; } set { root = Math.Max(24, Math.Min(60, value)); } }
        public int ActiveNarrativeState { get { return activeNarrative; } }
        public MusicScale ActiveScale { get { return activeScale; } }
        public int ActiveRootMidi { get { return activeRoot; } }
        public long NextStepIndex { get { return step; } }
        public long NextStepSample { get { return ToSample(nextStepTime); } }

        /// <summary>Restores defaults and a fresh frame-zero epoch; caller must clear old queued events.</summary>
        public void Reset(int sampleRate, uint seed)
        {
            this.sampleRate = Math.Max(32000, Math.Min(96000, sampleRate));
            randomState = seed == 0 ? 0x6D2B79F5u : seed;
            step = 0; nextStepTime = 0; hasPendingOff = false; pendingOff = default;
            root = activeRoot = 36; scale = activeScale = MusicScale.Minor;
            tempo = activeTempo = 112;
            requested = smooth = new GameMusicState { PlayerHealth = 1 };
            densityBand = articulationBand = narrativeCandidate = candidateBeats = activeNarrative = motif = 0;
        }

        public void SetState(GameMusicState state)
        {
            state.Danger = Finite(state.Danger, 0, 1, 0);
            state.EnemyProximity = Finite(state.EnemyProximity, 0, 1, 0);
            state.PlayerHealth = Finite(state.PlayerHealth, 0, 1, 1);
            state.MovementSpeed = Finite(state.MovementSpeed, 0, 1, 0);
            state.Weather = Finite(state.Weather, 0, 1, 0);
            requested = state;
        }

        /// <summary>
        /// Writes sorted events with Sample &lt;= throughSample. Empty buffers consume
        /// nothing. A pending note-off survives capacity-one calls. At most 4096
        /// grid steps are considered per call; call again to finish large horizons.
        /// SetState cannot revise musical decisions already generated by look-ahead.
        /// </summary>
        public int Fill(long throughSample, SynthEvent[] destination)
        {
            if (destination == null) throw new ArgumentNullException(nameof(destination));
            if (destination.Length == 0 || throughSample < 0) return 0;
            int written = 0, considered = 0;
            while (written < destination.Length && considered < 4096)
            {
                long nextSample = ToSample(nextStepTime);
                if (hasPendingOff && pendingOff.Sample <= nextSample)
                {
                    if (pendingOff.Sample > throughSample) break;
                    destination[written++] = pendingOff;
                    hasPendingOff = false;
                    continue;
                }
                if (nextSample > throughSample || nextSample == long.MaxValue) break;

                int phraseStep = (int)(step & 15);
                if ((phraseStep & 3) == 0) ApplyBeat(phraseStep == 0);
                double duration = sampleRate * 60.0 / (activeTempo * 4.0);
                uint rhythm = NextRandom(), pitch = NextRandom(), accent = NextRandom();
                int density = densityBand == 0 ? 35 : densityBand == 1 ? 60 : 85;
                bool play = phraseStep == 0 || (phraseStep != 15 && rhythm % 100 < density);
                if (play)
                {
                    int[] intervals = activeScale == MusicScale.Minor ? MinorIntervals : activeScale == MusicScale.Dorian ? DorianIntervals : PentatonicIntervals;
                    int degree = phraseStep == 0 ? 0 : (phraseStep / 2 + motif + (int)(pitch % 3)) % intervals.Length;
                    int note = activeRoot + intervals[degree];
                    bool accented = (phraseStep & 3) == 0 || accent % 5 == 0;
                    float velocity = accented ? .96f : .62f + .04f * (accent % 5);
                    destination[written++] = SynthEvent.On(nextSample, note, velocity);
                    double gate = articulationBand == 0 ? .90 : articulationBand == 1 ? .65 : .40;
                    pendingOff = SynthEvent.Off(Math.Max(nextSample + 1, ToSample(nextStepTime + duration * gate)), note);
                    hasPendingOff = true;
                }
                nextStepTime += duration;
                step++;
                considered++;
            }
            return written;
        }

        private void ApplyBeat(bool phraseStart)
        {
            activeTempo = tempo;
            densityBand = HysteresisBand(requested.Danger, densityBand);
            articulationBand = HysteresisBand(requested.MovementSpeed, articulationBand);
            if (requested.NarrativeState != narrativeCandidate)
            {
                narrativeCandidate = requested.NarrativeState;
                candidateBeats = 1;
            }
            else candidateBeats = Math.Min(2, candidateBeats + 1);
            if (phraseStart)
            {
                if (step == 0 || candidateBeats >= 2) activeNarrative = narrativeCandidate;
                activeRoot = root;
                activeScale = scale;
                // Unsigned folding is defined even for negative narrative identifiers.
                motif = (int)(unchecked((uint)activeNarrative * 2654435761u + NextRandom() % 3) % 7);
            }
        }

        /// <summary>
        /// Immediate expression: 200 ms one-pole time constant, dt seconds clamped
        /// 0..1. Pass the unadapted base preset every call, not the previous result.
        /// Wavetable position is audible only when a wavetable oscillator is selected.
        /// </summary>
        public SynthParameters AdaptPreset(SynthParameters basis, float elapsedSeconds)
        {
            basis.Sanitize();
            float dt = Finite(elapsedSeconds, 0, 1, 0);
            float amount = (float)(1 - Math.Exp(-dt / .2));
            smooth.Danger += (requested.Danger - smooth.Danger) * amount;
            smooth.EnemyProximity += (requested.EnemyProximity - smooth.EnemyProximity) * amount;
            smooth.PlayerHealth += (requested.PlayerHealth - smooth.PlayerHealth) * amount;
            smooth.Weather += (requested.Weather - smooth.Weather) * amount;
            basis.CutoffHz *= (float)Math.Pow(2, 4 * smooth.EnemyProximity);
            basis.PreDrive += (12 - basis.PreDrive) * .65f * smooth.Danger;
            basis.WavetablePosition += (1 - basis.WavetablePosition) * (1 - smooth.PlayerHealth);
            basis.NoiseLevel += .12f * smooth.Weather;
            basis.Sanitize();
            return basis;
        }

        private static int HysteresisBand(float value, int band)
        {
            // Schmitt thresholds: 0.33 and 0.67, with +/-0.05 deadbands.
            if (band == 0) return value > .72f ? 2 : value > .38f ? 1 : 0;
            if (band == 2) return value < .28f ? 0 : value < .62f ? 1 : 2;
            return value < .28f ? 0 : value > .72f ? 2 : 1;
        }

        private uint NextRandom()
        {
            uint x = randomState;
            x ^= x << 13; x ^= x >> 17; x ^= x << 5;
            randomState = x;
            return x;
        }

        private static long ToSample(double value)
        {
            return value >= long.MaxValue - 4096.0 ? long.MaxValue : (long)Math.Floor(value + .5);
        }

        private static float Finite(float value, float min, float max, float fallback)
        {
            return float.IsNaN(value) || float.IsInfinity(value) ? fallback : Math.Max(min, Math.Min(max, value));
        }
    }
}
